### ISSUE TITLE
In spring is there any where to ensure that the response is not transformed in the event of non HTTP 200 in rest calls

### ISSUE THREAD

**Issue by timothy-mugayi** [bohnman/squiggly-java#50]
For example if non error 200 response e.g 4xx the response may contain properties that fields inclusion list, is not able to match Is there a way to by pass response transformation so that certain responses are not affected by the field inclusion param?

**Comment by bohnman** [comment]
@timothy-mugayi I have released version 1.3.12 of Squiggly, which will only apply the filter if the status code is 2xx.  To see this in action, I have updated the spring boot example.  After running ``mvn spring-boot:run`` and you ``curl http://localhost:8080/issues/ISSUE-1?fields=id``, you will see the fields being filtered.  However, if you ``curl http://localhost:8080/issues/foo?fields=id``, you will see an  error message, which is not being filtered.

**Comment by bohnman** [comment]
@timothy-mugayi I have released another new version 1.3.13.  Upon review, I realized I was using a wildly outdated servlet spec, which didn't expose a getStatus method on the HttpServletResponse, causing me to create a response wrapper that did.  I updated the servlet api dependency, which eliminated the need for the wrapper.

**Comment by timothy-mugayi** [comment]
@bohnman Thanks, will have a look

**Comment by bohnman** [comment]
I'm assuming this is fixed.  Please re-open if not.

**Comment by fenjen** [comment]
@bohnman This is a very clever feature, but I have a problem using it. I'm going to describe what happens here.

**Setting**
The request URL doesn't exist (404), and my response entity to that shall be a Map with the values "details", "message" and "time" (showing the user what was wrong with the request). Of course, I don't want Squiggly to filter these values.

**Problem**
Now if I do specify "?field=myField", I'll get an empty response. But because of this feature here, the response should contain all fields, that is "details", "message" and "time".

**Analysis**
Squiggly saves the response in a ThreadLocal (SquigglyResponseHolder) as part of the filter chain to be able to determine the response status code when later processing the request. But Jersey creates another Response object (in my case in WebApplicationImpl.handleRequest(ContainerRequest, ContainerResponseWriter), line 1405, ***). Now, when Squiggly checks whether filtering is enabled (RequestSquigglyContextProvider), it checks the original response, which still has 200. Because the response code is 200, Squiggly filters everything (none of the three fields match "myField") and the response is empty.

While finding a workaround, I stumbled over a strange thing which is probably part of the problem: When I filter the _first_ field of my error object, `?fields=details`, I correctly (!) get the entire response object including details, message and time. What happens in that case is this:

1.  Squiggly checks the original response object, which shows 200 (should be 404) -> filtering=true
2. Squiggly sees "details" is in the list of requested fields, so it will serialize that value.
3. This value is written to the output stream, which triggers Jackson to initialize the original response object. Which includes writing headers. The former status=200 becomes 404 now. This happens in WebComponent.writeStatus(), `response.setStatus(statusType.getStatusCode(), reasonPhrase)`, line 277.
4. Squiggly encounters "time" and "message" each, and doesn't apply the filter, because it sees 404 now.

Is that a bug or do I have an unsupported setup? How can I get around this problem?

Also, please let me now if I can provide more details. Thanks!

*** I'm using Jersey, Jackson and Guice, `com.sun.jersey.guice.spi.container.servlet.GuiceContainer`

**Comment by bohnman** [comment]
@fenjen 

Great detail in explaining your issue!  Unfortunately, I've never used Jersey before so I'm not familiar with its internals.  However, if you would be able to provide me with a zip of a minimal Maven project exhibiting this behavior, I'd be happy to look into it!

**Comment by fenjen** [comment]
@bohnman Yep. Please tell me, if you need more.

[squiggly.issue_50.zip](https://github.com/bohnman/squiggly-java/files/3082089/squiggly.issue_50.zip)

**Comment by bohnman** [comment]
@fenjen

I have released version 1.3.17.

 I have 2 solutions for you:

[fix1.zip](https://github.com/bohnman/squiggly-java/files/3101415/fix1.zip)

fix1 uses a ContainerResponseFilter to set the real status code as a request attribute, which squiggly then checks.

[fix2.zip](https://github.com/bohnman/squiggly-java/files/3101418/fix2.zip)

fix2 uses a custom error object and then Squiggly turns off filtering if the objects being serialized is the custom error object.

Hope this helps!

~Ryan

**Comment by fenjen** [comment]
@bohnman Thank you very much! That works!
